In [1]:
import os
from os import listdir
from os.path import isfile, join
import cv2
import numpy as np
import os
from PIL import Image, ImageOps
# Import the matplotlib libraries
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow
import matplotlib.image as im
import numpy as np
from PIL import Image

In [92]:
boots = os.listdir("normalized_imgs/boots")

In [3]:
directories = os.listdir("normalized_imgs/")

In [51]:
len(os.listdir(os.getcwd()+"/normalized_imgs/hardshell_jackets"))

459

In [5]:
boots = [np.array(Image.open('normalized_imgs/boots/'+img)) for img in boots]


In [38]:
final_imgs_features = []
final_imgs_labels = []
dir_order = []
for subdir in directories:
    
    filepaths = os.listdir("normalized_imgs/"+subdir)
    for img in filepaths:
    #arr = [np.array(Image.open('normalized_imgs/{0}/'.format(subdir)+img)) for img in filepaths]
        img = np.array(Image.open('normalized_imgs/{0}/'.format(subdir)+img)).flatten()
        final_imgs_features.append(img)
        final_imgs_labels.append(subdir)
    dir_order.append(subdir)

In [48]:
# final_imgs
# Final Images is an array of arrays. The arrays within final_imgs are arrays of the images within each subdirectory
# final_imgs
# ---boots
# ------numpy array for image1
# ------numpy array for image2
# ------...
# ---hardshell_jackets
# ---...
print(len(final_imgs_features))

2122


Split the Data
________________

In [20]:
from sklearn.model_selection import train_test_split

In [40]:
x_train, x_test, y_train, y_test = train_test_split(final_imgs_features, final_imgs_labels, test_size=0.25, random_state=42)

In [41]:
x_train

[array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 253, ..., 255, 255, 253], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 2

In [24]:
from sklearn import svm

In [26]:
clf = svm.SVC()

In [42]:
# Returns our classifier, which is what we used to predict
clf.fit(x_train, y_train)
print("...Done!")

...Done!


In [46]:
results = clf.predict(x_test)

In [55]:
print(results)

['hardshell_jackets' 'hardshell_jackets' 'hardshell_jackets'
 'hardshell_jackets' 'hardshell_jackets' 'hardshell_jackets'
 'hardshell_jackets' 'hardshell_jackets' 'hardshell_jackets'
 'hardshell_jackets' 'hardshell_jackets' 'hardshell_jackets'
 'hardshell_jackets' 'hardshell_jackets' 'hardshell_jackets'
 'hardshell_jackets' 'hardshell_jackets' 'hardshell_jackets'
 'hardshell_jackets' 'hardshell_jackets' 'hardshell_jackets'
 'hardshell_jackets' 'hardshell_jackets' 'hardshell_jackets'
 'hardshell_jackets' 'hardshell_jackets' 'hardshell_jackets'
 'hardshell_jackets' 'hardshell_jackets' 'hardshell_jackets'
 'hardshell_jackets' 'hardshell_jackets' 'hardshell_jackets'
 'hardshell_jackets' 'hardshell_jackets' 'hardshell_jackets'
 'hardshell_jackets' 'hardshell_jackets' 'hardshell_jackets'
 'hardshell_jackets' 'hardshell_jackets' 'hardshell_jackets'
 'hardshell_jackets' 'hardshell_jackets' 'hardshell_jackets'
 'hardshell_jackets' 'hardshell_jackets' 'hardshell_jackets'
 'hardshell_jackets' 'ha

In [57]:
y_test

['tents',
 'carabiners',
 'gloves',
 'hardshell_jackets',
 'pulleys',
 'insulated_jackets',
 'hardshell_jackets',
 'hardshell_jackets',
 'carabiners',
 'insulated_jackets',
 'hardshell_jackets',
 'insulated_jackets',
 'tents',
 'harnesses',
 'axes',
 'boots',
 'carabiners',
 'gloves',
 'hardshell_jackets',
 'insulated_jackets',
 'insulated_jackets',
 'gloves',
 'crampons',
 'crampons',
 'rope',
 'rope',
 'rope',
 'hardshell_jackets',
 'hardshell_jackets',
 'hardshell_jackets',
 'hardshell_jackets',
 'carabiners',
 'hardshell_jackets',
 'hardshell_jackets',
 'hardshell_jackets',
 'carabiners',
 'crampons',
 'tents',
 'carabiners',
 'tents',
 'gloves',
 'boots',
 'rope',
 'boots',
 'crampons',
 'carabiners',
 'harnesses',
 'insulated_jackets',
 'rope',
 'carabiners',
 'gloves',
 'insulated_jackets',
 'axes',
 'tents',
 'carabiners',
 'insulated_jackets',
 'harnesses',
 'hardshell_jackets',
 'hardshell_jackets',
 'hardshell_jackets',
 'hardshell_jackets',
 'carabiners',
 'hardshell_jacket

In [58]:
from sklearn.linear_model import LogisticRegression

In [59]:
# all parameters not specified are set to their defaults
logisticRegr = LogisticRegression()

In [60]:
logisticRegr.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [61]:
logisticRegr.predict(x_test)

array(['tents', 'carabiners', 'gloves', 'insulated_jackets', 'pulleys',
       'insulated_jackets', 'hardshell_jackets', 'hardshell_jackets',
       'carabiners', 'insulated_jackets', 'hardshell_jackets',
       'insulated_jackets', 'tents', 'harnesses', 'carabiners', 'boots',
       'carabiners', 'gloves', 'hardshell_jackets', 'hardshell_jackets',
       'insulated_jackets', 'gloves', 'crampons', 'crampons', 'rope',
       'rope', 'rope', 'hardshell_jackets', 'insulated_jackets',
       'hardshell_jackets', 'hardshell_jackets', 'carabiners',
       'hardshell_jackets', 'hardshell_jackets', 'insulated_jackets',
       'carabiners', 'crampons', 'helmets', 'carabiners', 'tents',
       'gloves', 'boots', 'crampons', 'boots', 'crampons', 'carabiners',
       'harnesses', 'insulated_jackets', 'rope', 'carabiners', 'gloves',
       'insulated_jackets', 'helmets', 'tents', 'carabiners',
       'insulated_jackets', 'harnesses', 'hardshell_jackets',
       'hardshell_jackets', 'hardshell_jacke

In [62]:
y_test

['tents',
 'carabiners',
 'gloves',
 'hardshell_jackets',
 'pulleys',
 'insulated_jackets',
 'hardshell_jackets',
 'hardshell_jackets',
 'carabiners',
 'insulated_jackets',
 'hardshell_jackets',
 'insulated_jackets',
 'tents',
 'harnesses',
 'axes',
 'boots',
 'carabiners',
 'gloves',
 'hardshell_jackets',
 'insulated_jackets',
 'insulated_jackets',
 'gloves',
 'crampons',
 'crampons',
 'rope',
 'rope',
 'rope',
 'hardshell_jackets',
 'hardshell_jackets',
 'hardshell_jackets',
 'hardshell_jackets',
 'carabiners',
 'hardshell_jackets',
 'hardshell_jackets',
 'hardshell_jackets',
 'carabiners',
 'crampons',
 'tents',
 'carabiners',
 'tents',
 'gloves',
 'boots',
 'rope',
 'boots',
 'crampons',
 'carabiners',
 'harnesses',
 'insulated_jackets',
 'rope',
 'carabiners',
 'gloves',
 'insulated_jackets',
 'axes',
 'tents',
 'carabiners',
 'insulated_jackets',
 'harnesses',
 'hardshell_jackets',
 'hardshell_jackets',
 'hardshell_jackets',
 'hardshell_jackets',
 'carabiners',
 'hardshell_jacket

In [64]:
from sklearn import datasets, model_selection
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

In [88]:
def skl_knn(k, test_data, test_target, stored_data, stored_target):
    """k: number of neighbors to use in classication
    test_data: the data/targets used to test the classifier
    stored_data: the data/targets used to classify the test_data
    """
    
    classifier = KNeighborsClassifier(n_neighbors=k)  
    classifier.fit(stored_data, stored_target)

    y_pred = classifier.predict(test_data) 

    print(classification_report(test_target, y_pred))
    return classifier

ValueError: Mix type of y not allowed, got types {'multiclass', 'multiclass-multioutput'}

In [90]:
# our model
knn_model = skl_knn(8, x_test, y_test, x_train, y_train)

                   precision    recall  f1-score   support

             axes       0.90      0.90      0.90        21
            boots       1.00      0.97      0.98        30
       carabiners       0.97      0.94      0.95        78
         crampons       1.00      0.70      0.83        27
           gloves       0.97      0.74      0.84        53
hardshell_jackets       0.62      0.94      0.75       121
        harnesses       1.00      0.83      0.91        42
          helmets       1.00      0.56      0.72        16
insulated_jackets       0.68      0.46      0.55        57
          pulleys       1.00      0.17      0.29        12
             rope       0.80      0.72      0.76        46
            tents       0.74      1.00      0.85        28

      avg / total       0.84      0.80      0.80       531



In [91]:
# used to predict
knn_model.predict([testimglist[0]])


array(['helmets'], dtype='<U17')

In [95]:
import pickle
pickle.dump(knn_model, open( "knn_model.pkl", "wb" ) )

In [97]:
to_pickle = [x_test, y_test, x_train, y_train]
names = ["x_test", "y_test", "x_train", "y_train"]
for i in range(0, len(names)):
    pickle.dump(to_pickle[i], open( "{0}.pkl".format(names[i]), "wb" ) )

In [98]:
pickle.dump(final_imgs_features, open( "features.pkl", "wb" ) )
pickle.dump(final_imgs_labels, open( "labels.pkl", "wb" ) )

In [69]:
!curl -O https://shop.epictv.com/sites/default/files/ae42ad29e70ba8ce6b67d3bdb6ab5c6e.jpeg

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  167k  100  167k    0     0   110k      0  0:00:01  0:00:01 --:--:--  110k


In [80]:
def pad_and_resize(im_pth, desired_size):
    im = cv2.imread(im_pth)
    old_size = im.shape[:2] # old_size is in (height, width) format
    print(old_size)

    ratio = float(desired_size)/max(old_size)
    new_size = tuple([int(x*ratio) for x in old_size])

    # new_size should be in (width, height) format

    im = cv2.resize(im, (new_size[1], new_size[0]))

    delta_w = desired_size - new_size[1]
    delta_h = desired_size - new_size[0]
    top, bottom = delta_h//2, delta_h-(delta_h//2)
    left, right = delta_w//2, delta_w-(delta_w//2)

    color = [255, 255, 255]
    new_im = cv2.copyMakeBorder(im, top, bottom, left, right, cv2.BORDER_CONSTANT,
        value=color)
    cv2.imwrite(im_pth, new_im)
    return new_im

import numpy as np
from PIL import Image

def normalize(arr):
    """
    Linear normalization
    http://en.wikipedia.org/wiki/Normalization_%28image_processing%29
    """
    arr = arr.astype('float')
    # Do not touch the alpha channel
    for i in range(3):
        minval = arr[...,i].min()
        maxval = arr[...,i].max()
        if minval != maxval:
            arr[...,i] -= minval
            arr[...,i] *= (255.0/(maxval-minval))
    return arr

def demo_normalize(FILENAME):
    subdir = FILENAME.split("/")[-2]
    fileName = FILENAME.split("/")[-1]
    img = Image.open(FILENAME).convert('RGB')
    arr = np.array(img)
    new_img = Image.fromarray(normalize(arr).astype('uint8'),'RGB')
    if (os.path.exists('normalized_imgs/{0}'.format(subdir)) == False):
        os.makedirs('normalized_imgs/{0}'.format(subdir))
    new_img.save('normalized_imgs/{0}/{1}'.format(subdir, fileName))
    
def to_normalize(FILENAME):
    img = Image.open(FILENAME).convert('RGB')
    arr = np.array(img)
    new_img = Image.fromarray(normalize(arr).astype('uint8'),'RGB')
    return new_img

In [76]:
pad_and_resize("ae42ad29e70ba8ce6b67d3bdb6ab5c6e.jpeg", 128)

(128, 128)


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [83]:
testimglist = [np.array(to_normalize("ae42ad29e70ba8ce6b67d3bdb6ab5c6e.jpeg")).flatten(), "helmet"]

In [84]:
testimglist[0]

array([255, 255, 255, ..., 255, 255, 255], dtype=uint8)

In [86]:
skl_knn(8, [testimglist[0]], [testimglist[1]], x_train, y_train)

             precision    recall  f1-score   support

     helmet       0.00      0.00      0.00         1
    helmets       0.00      0.00      0.00         0

avg / total       0.00      0.00      0.00         1



/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
