In [114]:
import pickle
import numpy as np
def get_pkl(filename):
    with open(filename, 'rb') as f:
        return np.array(pickle.load(f))

### Load Pickle files
- `features` = All features
- `labels` = All labels
- `x_train` = Training features
- `y_train` = Training labels
- `x_test` = Test features
- `y_test` = Test labels

In [115]:
features = get_pkl('images_features.pkl')
labels = get_pkl('images_labels.pkl')

print('Feature shape:', features.shape)
print('Label shape:', labels.shape)

Feature shape: (2122, 128, 128, 3)
Label shape: (2122,)


In [130]:
features_update = np.array([img/255 for img in features])
features = features_update

### Get Validation Set
- From `x_train` and `y_train`, get 25% of the data as a validation set
- Will **still** be training on `x_train` and `y_train`

In [131]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features, labels, test_size=0.25, random_state=42)
new_x_train, x_validate, new_y_train, y_validate = train_test_split(x_train, y_train, test_size=0.25, random_state=42)

In [132]:
from numpy import array
from numpy import argmax
from keras.utils import to_categorical
x_train_encoded = to_categorical(y_train)
x_test_encoded = to_categorical(y_test)

ValueError: invalid literal for int() with base 10: 'carabiners'

In [38]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example

print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['carabiners' 'pulleys' 'gloves' ... 'insulated_jackets' 'rope'
 'harnesses']
[ 2  9  4 ...  8 10  6]
[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['carabiners']


/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [6]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [133]:
def OneHotCoder(val_arr):
    data = val_arr
    values = array(data)
    label_encoder = LabelEncoder()
    integer_encoded = label_encoder.fit_transform(values)
    onehot_encoder = OneHotEncoder(sparse=False)
    integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
    onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
    return onehot_encoded
y_train_encoded = OneHotCoder(y_train)
y_test_encoded = OneHotCoder(y_test)

### Goal
- Team will run a code cell in a Jupyter notebook for the coach that shows the model accuracy is 90% or greater (using the test data set from Challenge 3)
- Team will show logging that demonstrates validation accuracy that reaches 90% (using the validation dataset created in this challenge)

Suggested architecture:  
  
Input Layer (3 channel image input layer)  
Convolutional (2D)  
Max Pooling  
Convolutional (2D)  
Max Pooling  
Dense (Output layer)  

In [134]:
from keras.models import Sequential
import keras

filters = 10
kernel_size = (2,2)
model = Sequential()

In [135]:
from keras.models import Sequential
import keras

In [136]:
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten
model.add(Conv2D(filters, kernel_size, strides=(1, 1), input_shape=(128,128,3), activation='relu'))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters, kernel_size, strides=(1, 1), activation='relu'))
model.add(MaxPooling2D(pool_size=2))
model.add(Flatten())
model.add(Dense(units=12, activation='softmax'))

In [137]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_82 (Conv2D)           (None, 127, 127, 10)      130       
_________________________________________________________________
max_pooling2d_57 (MaxPooling (None, 63, 63, 10)        0         
_________________________________________________________________
conv2d_83 (Conv2D)           (None, 62, 62, 10)        410       
_________________________________________________________________
max_pooling2d_58 (MaxPooling (None, 31, 31, 10)        0         
_________________________________________________________________
flatten_24 (Flatten)         (None, 9610)              0         
_________________________________________________________________
dense_31 (Dense)             (None, 12)                115332    
Total params: 115,872
Trainable params: 115,872
Non-trainable params: 0
_________________________________________________________________


In [138]:
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

In [139]:
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.SGD(lr=0.01, momentum=0.9, nesterov=True))

In [140]:
# x_train and y_train are Numpy arrays --just like in the Scikit-Learn API.
model.fit(x_train, y_train_encoded, epochs=5, batch_size=32)

Epoch 1/5
1591/1591 [==============================] - 2s 1ms/step - loss: 2.3738
Epoch 2/5
1591/1591 [==============================] - 1s 703us/step - loss: 2.3475
Epoch 3/5
1591/1591 [==============================] - 1s 704us/step - loss: 2.3432
Epoch 4/5
1591/1591 [==============================] - 1s 714us/step - loss: 2.3414
Epoch 5/5
1591/1591 [==============================] - 1s 707us/step - loss: 2.3437


In [ ]:
model.evaluate(x_test, y_test_encoded, batch_size=128, verbose=0)

In [41]:
loss_and_metrics

12.44523409216642

In [141]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Dropout, Flatten
 
def createModel():
    model = Sequential()
    model.add(Conv2D(32, (3, 3), padding='same', activation='relu', input_shape=(128,128,3)))
    model.add(Conv2D(32, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))
 
    model.add(Conv2D(32, (3, 3), padding='same', activation='relu'))
    model.add(Conv2D(32, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))
 
    model.add(Conv2D(32, (3, 3), padding='same', activation='relu'))
    model.add(Conv2D(32, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))
    
 
    model.add(Flatten())
    model.add(Dense(512, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(len(set(y_train)), activation='softmax'))
     
    return model

In [142]:
model1 = createModel()
model1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_84 (Conv2D)           (None, 128, 128, 32)      896       
_________________________________________________________________
conv2d_85 (Conv2D)           (None, 126, 126, 32)      9248      
_________________________________________________________________
max_pooling2d_59 (MaxPooling (None, 63, 63, 32)        0         
_________________________________________________________________
dropout_32 (Dropout)         (None, 63, 63, 32)        0         
_________________________________________________________________
conv2d_86 (Conv2D)           (None, 63, 63, 32)        9248      
_________________________________________________________________
conv2d_87 (Conv2D)           (None, 61, 61, 32)        9248      
_________________________________________________________________
max_pooling2d_60 (MaxPooling (None, 30, 30, 32)        0         
__________

In [148]:
model1 = createModel()
batch_size = 64
epochs = 10
model1.compile(loss=keras.losses.binary_crossentropy,
              optimizer="adam",metrics=['accuracy'])
 
history = model1.fit(x_train, y_train_encoded, batch_size=batch_size, epochs=epochs)
 


Epoch 1/10
1591/1591 [==============================] - 5s 3ms/step - loss: 0.2782 - acc: 0.9167
Epoch 2/10
1591/1591 [==============================] - 4s 3ms/step - loss: 0.2745 - acc: 0.9167
Epoch 3/10
1591/1591 [==============================] - 4s 3ms/step - loss: 0.2732 - acc: 0.9167
Epoch 4/10
1591/1591 [==============================] - 4s 3ms/step - loss: 0.2733 - acc: 0.9167
Epoch 5/10
1591/1591 [==============================] - 4s 3ms/step - loss: 0.2715 - acc: 0.9167
Epoch 6/10
1591/1591 [==============================] - 4s 3ms/step - loss: 0.2430 - acc: 0.9190
Epoch 7/10
1591/1591 [==============================] - 4s 3ms/step - loss: 0.1522 - acc: 0.9439
Epoch 8/10
1591/1591 [==============================] - 4s 3ms/step - loss: 0.1067 - acc: 0.9578
Epoch 9/10
1591/1591 [==============================] - 4s 3ms/step - loss: 0.0811 - acc: 0.9685
Epoch 10/10
1591/1591 [==============================] - 4s 3ms/step - loss: 0.0698 - acc: 0.9709


In [149]:
results = model1.evaluate(x_test, y_test_encoded, batch_size=batch_size)


531/531 [==============================] - 1s 2ms/step


In [150]:
results

[0.07165455322874019, 0.973477720316296]